version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  dependencies:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-repo-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - "node_modules"
            
  publish-to-staging:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn netlify deploy -d . -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}
      - slack/notify:
          channel: noboru
          color: '#125d7d'
          message: (Staging) Hotel Example Site was successflly deployed

  publish-to-production:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn netlify deploy -p -d . -a ${NETLIFY_TOKEN} -s ${NETLIFY_API_ID}
      - slack/notify:
          channel: noboru
          color: '#3d7d12'
          message: (Production) Hotel Example Site was successflly deployed
      
workflows:
  version: 2
  Publish:
    jobs:
      - dependencies
      - publish-to-staging:
          filters:
            branches:
              only: development
          requires:
            - dependencies
      - publish-to-production:
          filters:
            branches:
              only: master
          requires:
            - dependencies
          
